"use client";

import { useEffect } from "react";
import type { LessonBlock, LessonModel } from "@/lib/content/types";
import { Markdown } from "@/components/Markdown";
import { ChoiceCheck } from "@/components/Checks";
import styles from "./ModuleFourLesson.module.css";

type ProseBlock = Extract<LessonBlock,{type:"prose"}>;
type QuickBlock = Extract<LessonBlock,{type:"quick-check"}>;
type SelfBlock = Extract<LessonBlock,{type:"self-check"}>;
type CompleteBlock = Extract<LessonBlock,{type:"module-complete"}>;
type NextBlock = Extract<LessonBlock,{type:"next-module"}>;
type Part={heading:string;body:string};
type Subsection={heading:string;body:string};
type ArtKind="hero"|"grid"|"perseus"|"theseus"|"heracles"|"jason"|"achilles"|"batumi";

const art:Record<ArtKind,{src:string;width:number;height:number;ru:string;en:string}>={
  hero:{src:"/visuals/module-04/01-HERO-heroes-world.webp",width:1536,height:1024,ru:"Мир героев древнегреческой мифологии.",en:"The world of heroes in Greek mythology."},
  grid:{src:"/visuals/module-04/02-HEROES-six-grid.webp",width:1536,height:1024,ru:"Шесть героев.",en:"Six heroes."},
  perseus:{src:"/visuals/module-04/03-PERSEUS-medusa-reflection.webp",width:1672,height:941,ru:"Персей смотрит на отражение Медузы в щите.",en:"Perseus looks at Medusa through her reflection in the shield."},
  theseus:{src:"/visuals/module-04/04-THESEUS-ariadne-thread.webp",width:1536,height:1024,ru:"Ариадна передаёт Тесею нить у Лабиринта.",en:"Ariadne gives Theseus the thread by the Labyrinth."},
  heracles:{src:"/visuals/module-04/05-HERACLES-hydra-cerberus.webp",width:1942,height:809,ru:"Геракл между Гидрой и Цербером.",en:"Heracles between the Hydra and Cerberus."},
  jason:{src:"/visuals/module-04/06-JASON-medea-golden-fleece.webp",width:1536,height:1024,ru:"Ясон, Медея и Золотое руно.",en:"Jason, Medea and the Golden Fleece."},
  achilles:{src:"/visuals/module-04/07-ACHILLES-ODYSSEUS-split.webp",width:1672,height:941,ru:"Ахиллес и Одиссей.",en:"Achilles and Odysseus."},
  batumi:{src:"/visuals/module-04/08-BATUMI-medea-square-local.webp",width:2048,height:1036,ru:"Статуя Медеи на площади Европы в Батуми.",en:"The Medea statue in Europe Square, Batumi."},
};

const copy={
  ru:{
    module:"МОДУЛЬ 04 / 08",nav:["Что такое герой","Персей","Тесей","Геракл","Ясон","Ахиллес","Одиссей"],
    markers:["01 / СНАЧАЛА","02–04 / ПЕРСЕЙ","05–07 / ТЕСЕЙ","08–11 / ГЕРАКЛ","12–17 / ЯСОН И МЕДЕЯ","18–21 / АХИЛЛЕС","22–23 / ОДИССЕЙ","24 / СОБИРАЕМ ГЕРОЕВ"],
    quick:"БЫСТРАЯ ПРОВЕРКА",self:"SELF-CHECK",selfTitle:"Проверяем основные связи",selfIntro:"Как обычно — не способность запомнить список родственников.",remember:"ЕСЛИ ЗАПОМНИТЬ ТОЛЬКО СЕМЬ ВЕЩЕЙ",rememberTitle:"Семь связей",completed:"MODULE COMPLETED",next:"ДАЛЬШЕ",continue:"Продолжить",nextLabel:"Дальше — истории",progress:"04 / 08",
    artLabels:["ПЕРСЕЙ / МЕДУЗА / ОТРАЖЕНИЕ","ТЕСЕЙ / АРИАДНА / НИТЬ","ГЕРАКЛ / ГИДРА / ЦЕРБЕР","ЯСОН / МЕДЕЯ / ЗОЛОТОЕ РУНО"],
    openingQuote:"«Да, звучит опасно.\nЯ пойду».",
    side:{read:"КАК ЧИТАТЬ ЭТОТ МОДУЛЬ",readTitle:"Не «кто хороший?»",readText:"Смотрим, какую проблему герой получает и как именно он её решает.",readBig:"задача → решение → след в культуре"},
    heroes:[["Персей","→ Медуза"],["Тесей","→ Лабиринт"],["Геракл","→ 12 подвигов"],["Ясон","→ Золотое руно"],["Ахиллес","→ уязвимое место"],["Одиссей","→ дорога домой"]],
    heroesClose:[["Персей","Медуза · отражение"],["Тесей","Лабиринт · нить"],["Геракл","12 подвигов · невозможное"],["Ясон","Колхида · Медея · Руно"],["Ахиллес","Троя · уязвимое место"],["Одиссей","ум · дорога домой"]],
    visual1Title:"Шесть героев — шесть ассоциаций",visual1Text:"Пока без подробностей. В конце модуля вернёмся к этой же схеме.",
    perseusFlow:["Нужно победить Медузу","❌ Смотреть прямо нельзя","🛡️ смотреть на отражение","⚔️ Персей побеждает Медузу"],
    perseusCaption:"Проблему решили не силой. Изменили способ взаимодействия с ней.",pegasus:["Персей","Медуза","Пегас","Эта связь вернётся позже."],
    thread:[["🗺️ карта","нет"],["🧙 магия","нет"],["🧵 нитка","да"]],threadQuote:"Иногда MVP действительно достаточно.",
    amathous:["Лабиринт на Крите","Тесей + Ариадна","одна из локальных традиций","Аматус, Кипр"],amathousCaption:"Мифы путешествуют вместе с людьми. Поэтому одна история может иметь несколько географий.",
    names:[["Greek","Heracles"],["Roman","Hercules"]],heraclesConnection:[["Гидра","Module 3"],["Геракл","12 подвигов"],["Цербер","Module 3"]],
    medeaLabels:["Медея","царевна Колхиды","Золотое руно"],
    geo:["Греция","Арго","Колхида","Медея","Золотое руно","Батуми"],
    compare:[["Ахиллес","почти непобедимый воин"],["Одиссей","ум, план, хитрость"]],
    timeline:[["Гомер","великий воин\nТроянская война\nникакого купания младенца в Стиксе"],["Поздняя традиция","Стикс\nнеуязвимое тело\nуязвимая пятка"],["Сегодня","“Achilles’ heel”\n= слабое место"]],
    odysseus:["Одиссей","Полифем","сын Посейдона","Посейдон очень недоволен","дорога домой становится ещё веселее"],
    strategy:[["Персей","🛡️ придумать обходной путь"],["Тесей","🧵 оставить путь назад"],["Геракл","💪 сделать невозможное"],["Ясон","⛵ собрать команду + принять помощь Медеи"],["Ахиллес","⚔️ быть практически непобедимым"],["Одиссей","🧠 перехитрить проблему"]],
    strategyCaption:"Один и тот же статус «герой». Совершенно разные способы действовать.",visual9Title:"Система за 10 секунд",visual9Text:"Возвращаем первую схему — теперь каждый герой уже связан с историей.",
  },
  en:{
    module:"MODULE 04 / 08",nav:["What is a hero?","Perseus","Theseus","Heracles","Jason","Achilles","Odysseus"],
    markers:["01 / FIRST","02–04 / PERSEUS","05–07 / THESEUS","08–11 / HERACLES","12–17 / JASON & MEDEA","18–21 / ACHILLES","22–23 / ODYSSEUS","24 / BUILD THE HERO MAP"],
    quick:"QUICK CHECK",self:"SELF-CHECK",selfTitle:"Check the main connections",selfIntro:"As usual — this is not about memorising a family tree.",remember:"IF YOU REMEMBER ONLY SEVEN THINGS",rememberTitle:"Seven connections",completed:"MODULE COMPLETED",next:"NEXT",continue:"Continue",nextLabel:"Next — stories",progress:"04 / 08",
    artLabels:["PERSEUS / MEDUSA / REFLECTION","THESEUS / ARIADNE / THREAD","HERACLES / HYDRA / CERBERUS","JASON / MEDEA / GOLDEN FLEECE"],
    openingQuote:"“Yes, sounds dangerous.\nI’ll go.”",
    side:{read:"HOW TO READ THIS MODULE",readTitle:"Not “who is good?”",readText:"Look at what problem each hero gets and exactly how they solve it.",readBig:"problem → solution → cultural trace"},
    heroes:[["Perseus","→ Medusa"],["Theseus","→ Labyrinth"],["Heracles","→ 12 Labours"],["Jason","→ Golden Fleece"],["Achilles","→ vulnerable point"],["Odysseus","→ journey home"]],
    heroesClose:[["Perseus","Medusa · reflection"],["Theseus","Labyrinth · thread"],["Heracles","12 Labours · impossible"],["Jason","Colchis · Medea · Fleece"],["Achilles","Troy · vulnerable point"],["Odysseus","intelligence · journey home"]],
    visual1Title:"Six heroes — six associations",visual1Text:"For now, without details. We will return to the same map at the end of the module.",
    perseusFlow:["Need to defeat Medusa","❌ Cannot look directly","🛡️ look at the reflection","⚔️ Perseus defeats Medusa"],
    perseusCaption:"The problem was not solved with more force. The way of interacting with it changed.",pegasus:["Perseus","Medusa","Pegasus","This connection will return later."],
    thread:[["🗺️ map","no"],["🧙 magic","no"],["🧵 thread","yes"]],threadQuote:"Sometimes an MVP is really enough.",
    amathous:["Labyrinth on Crete","Theseus + Ariadne","one local tradition","Amathous, Cyprus"],amathousCaption:"Myths travel with people. That is why one story can have several geographies.",
    names:[["Greek","Heracles"],["Roman","Hercules"]],heraclesConnection:[["Hydra","Module 3"],["Heracles","12 Labours"],["Cerberus","Module 3"]],
    medeaLabels:["Medea","princess of Colchis","Golden Fleece"],
    geo:["Greece","Argo","Colchis","Medea","Golden Fleece","Batumi"],
    compare:[["Achilles","almost unbeatable warrior"],["Odysseus","intelligence, plan, cunning"]],
    timeline:[["Homer","great warrior\nTrojan War\nno story of baby Achilles being dipped into the Styx"],["Later tradition","Styx\ninvulnerable body\nvulnerable heel"],["Today","“Achilles’ heel”\n= weak point"]],
    odysseus:["Odysseus","Polyphemus","son of Poseidon","Poseidon is very unhappy","the journey home gets even more entertaining"],
    strategy:[["Perseus","🛡️ find a workaround"],["Theseus","🧵 leave a way back"],["Heracles","💪 do the impossible"],["Jason","⛵ build a team + accept Medea’s help"],["Achilles","⚔️ be almost unbeatable"],["Odysseus","🧠 outsmart the problem"]],
    strategyCaption:"Same status: “hero”. Completely different ways of acting.",visual9Title:"The system in 10 seconds",visual9Text:"Return to the opening map — now every hero is connected with a story.",
  }
} as const;

async function post(url:string,body:unknown){const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r.json()}
function Art({kind,className="",eager=false,locale}:{kind:ArtKind;className?:string;eager?:boolean;locale:"ru"|"en"}){const a=art[kind];return <img className={className} src={a.src} width={a.width} height={a.height} alt={a[locale]} loading={eager?"eager":"lazy"} fetchPriority={eager?"high":"auto"} decoding={eager?"sync":"async"}/>}
function prose(model:LessonModel,n:number){const re=new RegExp(`^#\\s+${n}\\.`);const b=model.blocks.find(x=>x.type==="prose"&&re.test(x.markdown)) as ProseBlock|undefined;if(!b)throw new Error(`Module 4 missing section ${n}`);return b}
function specialProse(model:LessonModel,re:RegExp){const b=model.blocks.find(x=>x.type==="prose"&&re.test(x.markdown)) as ProseBlock|undefined;if(!b)throw new Error(`Module 4 missing prose ${re}`);return b}
function quick(model:LessonModel,n:number){const id=`quick-check-${String(n).padStart(2,"0")}`;const b=model.blocks.find(x=>x.type==="quick-check"&&x.id===id) as QuickBlock|undefined;if(!b)throw new Error(`Module 4 missing ${id}`);return b}
function selfCheck(model:LessonModel){const b=model.blocks.find(x=>x.type==="self-check") as SelfBlock|undefined;if(!b)throw new Error("Module 4 missing self-check");return b}
function completion(model:LessonModel){const b=model.blocks.find(x=>x.type==="module-complete") as CompleteBlock|undefined;if(!b)throw new Error("Module 4 missing completion");return b}
function nextBlock(model:LessonModel){const b=model.blocks.find(x=>x.type==="next-module") as NextBlock|undefined;if(!b)throw new Error("Module 4 missing next block");return b}
function rememberBlock(model:LessonModel){const b=model.blocks.find(x=>x.type==="prose"&&/^#\s+(?:If you remember only seven things|Если запомнить только семь вещей)/im.test(x.markdown)) as ProseBlock|undefined;if(!b)throw new Error("Module 4 missing remember");return b}
function displayify(s:string){return s.replace(/^#\s+/gm,"### ")}
function splitHeading(markdown:string):Part{const lines=markdown.split(/\r?\n/);const i=lines.findIndex(l=>/^#{1,6}\s+/.test(l));return i<0?{heading:"",body:displayify(markdown)}:{heading:lines[i].replace(/^#{1,6}\s+/,'').replace(/^\d+\.\s*/,'').trim(),body:displayify(lines.filter((_,n)=>n!==i).join("\n").trim())}}
function splitSubsections(markdown:string){const base=splitHeading(markdown);const lines=base.body.split(/\r?\n/);const ix:number[]=[];lines.forEach((l,i)=>{if(/^###\s+/.test(l))ix.push(i)});const intro=ix.length?lines.slice(0,ix[0]).join("\n").trim():base.body;const items:Subsection[]=ix.map((start,j)=>({heading:lines[start].replace(/^###\s+/,"").trim(),body:lines.slice(start+1,ix[j+1]??lines.length).join("\n").trim()}));return {heading:base.heading,intro,items}}
function introBody(markdown:string){let heads=0;return displayify(markdown.split(/\r?\n/).filter(l=>{if(/^#\s+/.test(l)&&heads<2){heads++;return false}if(/^\*\*(?:Время|Time):\*\*/.test(l))return false;return true}).join("\n").trim())}
function cleanCompletion(markdown:string){const p=splitHeading(markdown);const lines=p.body.split(/\r?\n/);const i=lines.findIndex(l=>l.trim());const heading=i>=0?lines[i].trim():p.heading;return {heading,body:lines.filter((_,n)=>n!==i).join("\n").trim()}}
function splitNext(markdown:string):Part{const lines=markdown.split(/\r?\n/);const first=lines.findIndex(l=>/^#\s+/.test(l));const second=lines.findIndex((l,i)=>i>first&&/^##\s+/.test(l));if(second<0)return splitHeading(markdown);return {heading:lines[second].replace(/^##\s+/,"").trim(),body:displayify(lines.filter((_,i)=>i!==first&&i!==second).join("\n").trim())}}

export function ModuleFourLesson({model}:{model:LessonModel}){
 const t=copy[model.locale], intro=specialProse(model,/^#\s+(?:Модуль 4|Module 4)/m);
 const s=Array.from({length:24},(_,i)=>splitHeading(prose(model,i+1).markdown));
 const cerberus=splitHeading(specialProse(model,/^###\s+(?:Цербер|Cerberus)/m).markdown);
 const qs=[1,2,3,4,5].map(n=>quick(model,n)), self=selfCheck(model), remember=splitSubsections(rememberBlock(model).markdown), complete=cleanCompletion(completion(model).markdown), next=splitNext(nextBlock(model).markdown);
 const selfIntroMarkdown=self.markdown.split(/\n-{3,}\n/)[0].replace(/^#\s+(?:Self-check|Самопроверка)\s*/i,"").trim();
 useEffect(()=>{post("/api/module/start",{moduleId:model.moduleId}).catch(()=>{})},[model.moduleId]);
 const persistCheck=(id:string,sourceIndex:number)=>post("/api/module/check",{moduleId:model.moduleId,checkId:id,sourceIndex}).catch(()=>{});
 async function finish(){await post("/api/module/complete",{moduleId:model.moduleId});location.href=`/${model.locale}/courses/greek-mythology/module-05`}
 const Quick=({n}:{n:number})=><div className={`${styles.quick} ${styles.reading}`}><p className={styles.marker}>{t.quick}</p><ChoiceCheck question={qs[n-1].question} locale={model.locale} onPersist={(v)=>persistCheck(qs[n-1].id,v)}/></div>;
 return <article className={styles.page}>
  <section className={styles.hero}><Art kind="hero" className={styles.heroImage} locale={model.locale} eager/><div className={styles.heroShade}/><div className={styles.heroInner}><div className={styles.heroCopy}><p className={styles.kicker}>{t.module}</p><h1>{model.title}</h1><p className={styles.duration}><span className={styles.clock}/>{model.durationLabel}</p></div></div></section>
  <nav className={styles.sectionNav} aria-label={model.locale==="ru"?"Навигация по модулю":"Module navigation"}>{t.nav.map((x,i)=><span className={styles.navItem} key={x}><a href={i===0?"#hero-meaning":`#${["perseus","theseus","heracles","jason","achilles","odysseus"][i-1]}`}>{x}</a>{i<t.nav.length-1&&<i/>}</span>)}</nav>
  <section className={styles.opening}><div className={`${styles.reading} ${styles.openingGrid}`}><div className={styles.rich}><Markdown>{introBody(intro.markdown)}</Markdown></div><blockquote className={styles.heroQuote}>{t.openingQuote.split("\n").map((x,i)=><span key={x}>{x}{i===0&&<br/>}</span>)}</blockquote></div></section>
  <section id="hero-meaning" className={styles.story}><div className={`${styles.reading} ${styles.storyGrid}`}><article><p className={styles.marker}>{t.markers[0]}</p><h2>{s[0].heading}</h2><div className={styles.rich}><Markdown>{s[0].body}</Markdown></div></article><aside className={styles.sideCard}><p className={styles.marker}>{t.side.read}</p><h3>{t.side.readTitle}</h3><p>{t.side.readText}</p><span className={styles.big}>{t.side.readBig}</span></aside></div></section>
  <section className={styles.visualStop}><div className={`${styles.reading} ${styles.intro}`}><p className={styles.marker}>{model.locale==="ru"?"ВИЗУАЛЬНАЯ ОСТАНОВКА 01":"VISUAL STOP 01"}</p><h2 className={styles.sectionTitle}>{t.visual1Title}</h2><p>{t.visual1Text}</p></div><figure className={styles.gridArt}><Art kind="grid" locale={model.locale}/></figure><div className={`${styles.reading} ${styles.heroMap}`}>{t.heroes.map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div></section>

  <section id="perseus" className={styles.story}><figure className={styles.fullArt}><Art kind="perseus" locale={model.locale}/><figcaption className={styles.artLabel}>{t.artLabels[0]}</figcaption></figure><div className={`${styles.reading} ${styles.storyGrid}`}><article><p className={styles.marker}>{t.markers[1]}</p><h2>{s[1].heading}</h2><div className={styles.rich}><Markdown>{s[1].body}</Markdown></div><h2>{s[2].heading}</h2><div className={styles.rich}><Markdown>{s[2].body}</Markdown></div></article><aside className={styles.sideCard}><p className={styles.marker}>{model.locale==="ru"?"ВИЗУАЛЬНАЯ ОСТАНОВКА 02":"VISUAL STOP 02"}</p><h3>{model.locale==="ru"?"Задача Персея":"Perseus’s task"}</h3><div className={`${styles.flow} ${styles.verticalFlow}`}>{t.perseusFlow.map((x,i)=><span className={i===3?styles.yes:""} key={x}>{x}{i<t.perseusFlow.length-1&&<i>↓</i>}</span>)}</div><p><strong>{t.perseusCaption}</strong></p></aside></div><Quick n={1}/><div className={`${styles.reading} ${styles.twoCol}`}><article><h2>{s[3].heading}</h2><div className={styles.rich}><Markdown>{s[3].body}</Markdown></div></article><aside className={styles.route}>{t.pegasus.slice(0,3).map((x,i)=><span key={x}><b>{x}</b>{i<2&&<i>↓</i>}</span>)}<small>{t.pegasus[3]}</small></aside></div></section>

  <section id="theseus" className={styles.story}><figure className={styles.fullArt}><Art kind="theseus" locale={model.locale}/><figcaption className={styles.artLabel}>{t.artLabels[1]}</figcaption></figure><div className={`${styles.reading} ${styles.twoCol}`}><article><p className={styles.marker}>{t.markers[2]}</p><h2>{s[4].heading}</h2><div className={styles.rich}><Markdown>{s[4].body}</Markdown></div></article><article><h2>{s[5].heading}</h2><div className={styles.rich}><Markdown>{s[5].body}</Markdown></div></article></div><div className={styles.reading}><p className={styles.marker}>{model.locale==="ru"?"ВИЗУАЛЬНАЯ ОСТАНОВКА 03":"VISUAL STOP 03"}</p><h2 className={styles.sectionTitle}>{model.locale==="ru"?"Лучшее решение не всегда самое сложное":"The best solution is not always the most complicated one"}</h2><div className={styles.threadPanel}>{t.thread.map((x,i)=><div className={i===2?styles.right:""} key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div><blockquote className={`${styles.heroQuote} ${styles.threadQuote}`}>{t.threadQuote}</blockquote></div><Quick n={2}/><div className={`${styles.reading} ${styles.storyGrid}`}><article><h2>{s[6].heading}</h2><div className={styles.rich}><Markdown>{s[6].body}</Markdown></div></article><aside className={styles.route}><p className={styles.marker}>{model.locale==="ru"?"ВИЗУАЛЬНАЯ ОСТАНОВКА 04":"VISUAL STOP 04"}</p>{t.amathous.map((x,i)=><span key={x}><b>{x}</b>{i<t.amathous.length-1&&<i>↓</i>}</span>)}<small>{t.amathousCaption}</small></aside></div></section>

  <section id="heracles" className={styles.story}><figure className={`${styles.fullArt} ${styles.heraclesArt}`}><Art kind="heracles" locale={model.locale}/><figcaption className={styles.artLabel}>{t.artLabels[2]}</figcaption></figure><div className={`${styles.reading} ${styles.storyGrid}`}><article><p className={styles.marker}>{t.markers[3]}</p><h2>{s[7].heading}</h2><div className={styles.rich}><Markdown>{s[7].body}</Markdown></div><div className={styles.nameSplit}><div><b>{t.names[0][0]}</b><span>{t.names[0][1]}</span></div><i>↔</i><div><b>{t.names[1][0]}</b><span>{t.names[1][1]}</span></div></div><h2>{s[8].heading}</h2><div className={styles.rich}><Markdown>{s[8].body}</Markdown></div></article><article><h2>{s[9].heading}</h2><div className={styles.rich}><Markdown>{s[9].body}</Markdown></div><h2>{s[10].heading}</h2><div className={styles.rich}><Markdown>{s[10].body}</Markdown></div><h2>{cerberus.heading}</h2><div className={styles.rich}><Markdown>{cerberus.body}</Markdown></div></article></div><div className={styles.reading}><p className={styles.marker}>{model.locale==="ru"?"ВИЗУАЛЬНАЯ ОСТАНОВКА 05":"VISUAL STOP 05"}</p><h2 className={styles.sectionTitle}>{model.locale==="ru"?"Вы уже знали два подвига, просто не знали, что знаете":"You already knew two Labours. You just did not know you knew them."}</h2><div className={styles.connection}>{t.heraclesConnection.map((x,i)=><div className={i===1?styles.center:""} key={x[0]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div></div><Quick n={3}/></section>

  <section id="jason" className={styles.story}><figure className={`${styles.fullArt} ${styles.jasonArt}`}><Art kind="jason" locale={model.locale}/><figcaption className={styles.artLabel}>{t.artLabels[3]}</figcaption></figure><div className={`${styles.reading} ${styles.twoCol}`}><article><p className={styles.marker}>{t.markers[4]}</p><h2>{s[11].heading}</h2><div className={styles.rich}><Markdown>{s[11].body}</Markdown></div></article><article><h2>{s[12].heading}</h2><div className={styles.rich}><Markdown>{s[12].body}</Markdown></div></article></div></section>
  <section className={styles.medeaPhoto}><div className={`${styles.reading} ${styles.intro}`}><p className={styles.marker}>{model.locale==="ru"?"ВИЗУАЛЬНАЯ ОСТАНОВКА 06":"VISUAL STOP 06"}</p><h2 className={styles.sectionTitle}>{model.locale==="ru"?"Вы могли проходить мимо неё десятки раз":"You may have walked past her dozens of times"}</h2></div><figure className={styles.medeaFigure}><Art kind="batumi" locale={model.locale}/><figcaption className={styles.medeaCaption}>{t.medeaLabels.map(x=><span key={x}>{x}</span>)}</figcaption></figure></section>
  <section className={styles.story}><div className={`${styles.reading} ${styles.twoCol}`}><article><h2>{s[13].heading}</h2><div className={styles.rich}><Markdown>{s[13].body}</Markdown></div></article><article><h2>{s[14].heading}</h2><div className={styles.rich}><Markdown>{s[14].body}</Markdown></div></article></div><div className={styles.reading}><h2 className={styles.sectionTitle}>{s[15].heading}</h2><div className={styles.rich}><Markdown>{s[15].body}</Markdown></div><div className={styles.geoChain}>{t.geo.map((x,i)=><span key={x}>{x}{i<t.geo.length-1&&<i>→</i>}</span>)}</div></div><Quick n={4}/><div className={`${styles.reading} ${styles.twoCol}`}><article><h2>{s[16].heading}</h2><div className={styles.rich}><Markdown>{s[16].body}</Markdown></div></article><aside className={styles.sideCard}><h3>{model.locale==="ru"?"Если видите...":"If you see..."}</h3><p><strong>Jason / Ясон</strong> — {model.locale==="ru"?"Золотое руно, Арго, аргонавты, Колхида, Медея.":"Golden Fleece, Argo, Argonauts, Colchis, Medea."}</p><p><strong>Odysseus / Одиссей</strong> — {model.locale==="ru"?"Троя, Итака, долгий путь домой.":"Troy, Ithaca, the long journey home."}</p></aside></div></section>

  <section id="achilles" className={styles.story}><div className={styles.compareHero}><figure><Art kind="achilles" locale={model.locale}/><figcaption><b>{t.compare[0][0]}</b><span>{t.compare[0][1]}</span></figcaption></figure><figure><Art kind="achilles" locale={model.locale}/><figcaption><b>{t.compare[1][0]}</b><span>{t.compare[1][1]}</span></figcaption></figure></div><div className={`${styles.reading} ${styles.twoCol}`}><article><p className={styles.marker}>{t.markers[5]}</p><h2>{s[17].heading}</h2><div className={styles.rich}><Markdown>{s[17].body}</Markdown></div></article><article><h2>{s[18].heading}</h2><div className={styles.rich}><Markdown>{s[18].body}</Markdown></div></article></div><div className={styles.reading}><div className={styles.achillesMore}><article><h2>{s[19].heading}</h2><div className={styles.rich}><Markdown>{s[19].body}</Markdown></div></article><article><h2>{s[20].heading}</h2><div className={styles.rich}><Markdown>{s[20].body}</Markdown></div></article></div><p className={styles.marker}>{model.locale==="ru"?"ВИЗУАЛЬНАЯ ОСТАНОВКА 07":"VISUAL STOP 07"}</p><h2 className={styles.sectionTitle}>{model.locale==="ru"?"Ахиллес: две традиции":"Achilles: two traditions"}</h2><div className={styles.timeline}>{t.timeline.map((x,i)=><div className={styles.timelineItem} key={x[0]}><div><b>{x[0]}</b><span>{x[1].split("\n").map(y=><em key={y}>{y}</em>)}</span></div>{i<t.timeline.length-1&&<i>→</i>}</div>)}</div></div><Quick n={5}/></section>

  <section id="odysseus" className={styles.story}><div className={`${styles.reading} ${styles.twoCol}`}><article><p className={styles.marker}>{t.markers[6]}</p><h2>{s[21].heading}</h2><div className={styles.rich}><Markdown>{s[21].body}</Markdown></div></article><article><h2>{s[22].heading}</h2><div className={styles.rich}><Markdown>{s[22].body}</Markdown></div><aside className={styles.route}>{t.odysseus.map((x,i)=><span key={x}><b>{x}</b>{i<t.odysseus.length-1&&<i>↓</i>}</span>)}</aside></article></div></section>
  <section className={styles.strategy}><div className={styles.reading}><p className={styles.marker}>{model.locale==="ru"?"ВИЗУАЛЬНАЯ ОСТАНОВКА 08":"VISUAL STOP 08"}</p><h2 className={styles.sectionTitle}>{model.locale==="ru"?"Герои решают проблемы по-разному":"Heroes solve problems differently"}</h2><div className={styles.strategyGrid}>{t.strategy.map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div><p className={styles.strategyCaption}><strong>{t.strategyCaption}</strong></p></div></section>
  <section className={styles.summary}><div className={styles.reading}><p className={styles.marker}>{t.markers[7]}</p><h2 className={styles.sectionTitle}>{model.locale==="ru"?"Теперь без подробностей":"Now without the details"}</h2><div className={styles.summaryGrid}>{splitSubsections(prose(model,24).markdown).items.map(item=><div className={styles.summaryCard} key={item.heading}><h3>{item.heading}</h3><div className={styles.rich}><Markdown>{item.body}</Markdown></div></div>)}</div></div></section>
  <section className={styles.visualStop}><div className={`${styles.reading} ${styles.intro}`}><p className={styles.marker}>{model.locale==="ru"?"ВИЗУАЛЬНАЯ ОСТАНОВКА 09":"VISUAL STOP 09"}</p><h2 className={styles.sectionTitle}>{t.visual9Title}</h2><p>{t.visual9Text}</p></div><figure className={styles.gridArt}><Art kind="grid" locale={model.locale}/></figure><div className={`${styles.reading} ${styles.heroMap}`}>{t.heroesClose.map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div></section>

  <section id="self-check" className={styles.selfCheck}><div className={styles.reading}><p className={styles.marker}>{t.self}</p><h2 className={styles.sectionTitle}>{t.selfTitle}</h2><div className={`${styles.rich} ${styles.selfIntro}`}><Markdown>{selfIntroMarkdown}</Markdown></div><div className={styles.selfGrid}>{self.questions.map((q,i)=><article className={styles.selfQ} key={q.id}><span className={styles.selfNum}>{String(i+1).padStart(2,"0")}</span><ChoiceCheck question={q} locale={model.locale} onPersist={(v)=>persistCheck(q.id,v)}/></article>)}</div></div></section>
  <section className={styles.remember}><div className={styles.reading}><p className={styles.marker}>{t.remember}</p><h2 className={styles.sectionTitle}>{t.rememberTitle}</h2><div className={styles.rememberGrid}>{remember.items.map((item,i)=><article className={styles.rememberCard} key={item.heading}><b>{String(i+1).padStart(2,"0")}</b><div className={styles.rich}><Markdown>{item.body}</Markdown></div></article>)}</div></div></section>
  <section className={styles.completion}><div className={`${styles.reading} ${styles.completionGrid}`}><article><p className={styles.marker}>{t.completed}</p><h2 className={styles.sectionTitle}>{complete.heading}</h2><div className={styles.network}><span>{model.locale==="ru"?"боги":"gods"}</span><i>→</i><span>{model.locale==="ru"?"монстры":"monsters"}</span><i>→</i><span>{model.locale==="ru"?"герои":"heroes"}</span></div><div className={styles.rich}><Markdown>{complete.body}</Markdown></div></article><aside className={styles.nextCard}><p className={styles.marker}>{t.next}</p><h3>{next.heading}</h3><div className={styles.rich}><Markdown>{next.body}</Markdown></div><button className={styles.continue} onClick={finish}>{t.continue} <span aria-hidden="true">→</span></button></aside></div></section>
 </article>
}